# Generated by Django 4.2.4 on 2023-08-05 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variactions',
            new_name='variations',
        ),
    ]
